# Generated by Django 5.2.1 on 2025-06-13 03:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "roles",
                    models.CharField(
                        choices=[("Standard", "standard"), ("Gold", "gold")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50, unique=True)),
                ("product_quantity", models.PositiveIntegerField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_description", models.CharField(max_length=100)),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("TV", "Tv"),
                            ("Acessories", "accessories"),
                            ("Phone", "phone"),
                            ("Laptop", "laptop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        upload_to="product_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_created", models.DateTimeField(auto_now_add=True)),
                (
                    "cart_customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estore.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loggin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "username_logging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estore.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_created", models.DateTimeField(auto_now_add=True)),
                (
                    "order_customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estore.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdereachProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_quantity", models.PositiveIntegerField()),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Estore.orders",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estore.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarteachProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cart_quantity", models.PositiveIntegerField()),
                (
                    "cart_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Estore.carts",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estore.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=50)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phonenumber", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "method",
                    models.CharField(
                        choices=[("standard", "Standard"), ("express", "Express")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("last_card_4number", models.CharField(max_length=4)),
                ("card_type", models.CharField(max_length=20)),
                ("paid_date", models.DateTimeField(auto_now_add=True)),
                ("payment_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Delivery Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "shipment_customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Estore.customer",
                    ),
                ),
            ],
        ),
    ]
