# Generated by Django 5.2.1 on 2025-06-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_description",
            field=models.TextField(),
        ),
    ]
