# Generated by Django 5.2.1 on 2025-06-14 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Estore", "0002_alter_products_product_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Loggin",
            new_name="Logging",
        ),
    ]
