# Generated by Django 5.2.1 on 2025-06-17 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Estore", "0003_rename_loggin_logging"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Carts",
            new_name="Cart",
        ),
        migrations.RenameModel(
            old_name="Orders",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
