# Generated by Django 5.2.1 on 2025-06-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estore", "0004_rename_carts_cart_rename_orders_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
