# Generated by Django 5.2.1 on 2025-06-24 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Estore", "0005_alter_customer_password"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrdereachProduct",
            new_name="OrdereachTransaction",
        ),
        migrations.RenameField(
            model_name="shipment",
            old_name="shipment_customer_id",
            new_name="customer",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="card_type",
        ),
    ]
