# Generated by Django 5.2.1 on 2025-06-24 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estore", "0006_rename_ordereachproduct_ordereachtransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="country",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="last_card_4number",
        ),
        migrations.AddField(
            model_name="order",
            name="order_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Estore.order",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="zip_code",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
